src/models/Log.php
<?php

namespace datait\fractal\models;

use Yii;
use yii\db\ActiveRecord;

class Log extends ActiveRecord {
	const TYPE_ACTION = 1;

	const KIND_WORKER = 1;
	const KIND_CUSTOMER = 2;
	const KIND_PROJECT = 3;
	const KIND_TASK = 4;
	const KIND_SCHEMA = 5;
	const KIND_INVOICE = 6;

	public static function tableName() {
		return 'tbl_log';
	}

	public function rules() {
		return [
			['fld_creator_id', 'exist', 'targetClass' => '\app\models\Account', 'targetAttribute' => 'fld_id', 'skipOnEmpty' => true],
			[['fld_type_id', 'fld_action_id', 'fld_kind_id', 'fld_object_id'], 'number'],
			[['fld_action_name', 'fld_action_color', 'fld_comment'], 'string'],

			[['fld_type_id', 'fld_action_id'], 'required'],
		];
	}

	public function attributeLabels() {
		return [
			'fld_action_name' => 'Nazwa akcji',
			'fld_type_id' => 'Typ',
			'fld_object_id' => 'Obiekt',
			'fld_created_at' => 'Data i czas',
			'fld_creator_id' => 'Utworzył',
		];
	}

	public function getCreator() {
		return $this->hasOne(Account::className(), ['fld_id' => 'fld_creator_id']);
	}

	public static function types() {
		return [
			self::TYPE_ACTION => ['fld_id' => self::TYPE_ACTION, 'fld_name' => 'Akcja', 'fld_color' => 'green'],
		];
	}

	public function getType() {
		return self::types()[$this->fld_type_id];
	}

	public static function kinds() {
		return [
			self::KIND_WORKER => ['fld_id' => self::KIND_WORKER, 'fld_name' => 'Pracownik', 'fld_view' => '/worker/view'],
			self::KIND_CUSTOMER => ['fld_id' => self::KIND_CUSTOMER, 'fld_name' => 'Klient', 'fld_view' => '/customer/view'],
			self::KIND_PROJECT => ['fld_id' => self::KIND_PROJECT, 'fld_name' => 'Projekt', 'fld_view' => '/project/view'],
			self::KIND_TASK => ['fld_id' => self::KIND_TASK, 'fld_name' => 'Praca', 'fld_view' => '/task/view'],
			self::KIND_SCHEMA => ['fld_id' => self::KIND_SCHEMA, 'fld_name' => 'Schemat rozliczeń', 'fld_view' => '/schema/view'],
		];
	}

	public static function kind($kind_id) {
		return self::kinds()[$kind_id];
	}

	public function getKind() {
		return self::kind($this->fld_kind_id);
	}

	public static function saveAction($kind_id, $action, $object_id, $comment = '') {
		$log = new Log;

		$log->fld_creator_id = Yii::$app->user->id;
		$log->fld_type_id = self::TYPE_ACTION;
		$log->fld_kind_id = $kind_id;
		$log->fld_action_id = $action['fld_id'];
		$log->fld_action_name = $action['fld_name'];
		$log->fld_action_color = $action['fld_color'];
		$log->fld_object_id = $object_id;
		$log->fld_comment = $comment;

		if (!$log->save()) {
			Yii::trace('Błąd zapisu loga do bazy danych ' . var_export($log, true));
		}
	}
}

src/models/Worker.php
<?php

namespace datait\fractal\models;

use Yii;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use function array_keys;
use function date;
use function implode;

/**
 * Class Worker
 * @package app\models
 *
 * @property int fld_id
 * @property int fld_type_id
 * @property int fld_status_id
 * @property string fld_last_name
 * @property string fld_first_name
 * @property string fld_email
 * @property string fld_mobile
 * @property string fld_description
 * @property int fld_created_at
 * @property int fld_creator_id
 * @property int fld_updated_at
 * @property int fld_updater_id
 * @property int fld_deleted_at
 * @property int fld_deleter_id
 */

class Worker extends ActiveRecord
{
    const ACTION_CREATE = 1;
    const ACTION_UPDATE = 2;
    const ACTION_STATUS = 3;

    const TYPE_EDITOR = 'editor';
    const TYPE_PARTNER = 'partner';
    const TYPE_WEBMASTER = 'webmaster';

    const STATUS_INACTIVE = 0;
    const STATUS_ACTIVE = 1;

    /**
     * @var array
     */
    private static $types = [
        self::TYPE_EDITOR => [
            'fld_id' => self::TYPE_EDITOR,
            'fld_name' => 'Edytor',
            'fld_class' => 'default',
            'role' => 'editor',
        ],
        self::TYPE_PARTNER => [
            'fld_id' => self::TYPE_PARTNER,
            'fld_name' => 'Administrator',
            'fld_class' => 'primary',
            'role' => 'partner',
        ],
        self::TYPE_WEBMASTER => [
            'fld_id' => self::TYPE_WEBMASTER,
            'fld_name' => 'Webmaster',
            'fld_class' => 'master',
            'role' => 'webmaster',
        ],
    ];

    /**
     * @var array
     */
    private static $statuses = [
        self::STATUS_INACTIVE => [
            'fld_name' => 'Nieaktywny',
            'fld_class' => 'danger',
        ],
        self::STATUS_ACTIVE => [
            'fld_name' => 'Aktywny',
            'fld_class' => 'success',
        ],
    ];

    /**
     * @return string
     */
    public static function tableName(): string
    {
        return 'tbl_worker';
    }

    /**
     * @return array
     */
    public function rules(): array
    {
        return [
            [['fld_last_name', 'fld_first_name', 'fld_email'], 'string'],
            ['fld_type_id', 'in', 'range' => array_keys(static::$types)],
            ['fld_status_id', 'in', 'range' => array_keys(static::$statuses)],
            ['fld_email', 'email'],
            ['fld_mobile', 'string'],
            ['fld_description', 'string'],
            [['fld_last_name', 'fld_type_id', 'fld_email'], 'required'],
            ['fld_status_id', 'default', 'value' => self::STATUS_ACTIVE],
        ];
    }

    /**
     * @return array
     */
    public function attributeLabels(): array
    {
        return [
            'fld_id' => 'Id',
            'fld_name' => 'Nazwa',
            'fld_last_name' => 'Nazwisko',
            'fld_first_name' => 'Imię',
            'fld_full_name' => 'Nazwisko i imię',
            'fld_email' => 'E-mail',
            'fld_mobile' => 'Telefon komórkowy',
            'fld_status_id' => 'Status',
            'fld_description' => 'Opis',
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getAccount(): ActiveQuery
    {
        return $this->hasOne(
            Account::class,
            [
                'fld_model_id' => 'fld_id',
            ]
        )
        ->onCondition([
            'fld_class_id' => 'cmsUser',
        ]);
    }

    /**
     * @return ActiveQuery
     */
    public function getCreator(): ActiveQuery
    {
        return $this->hasOne(
            Account::class,
            [
                'fld_id' => 'fld_creator_id',
            ]
        );
    }

    /**
     * @return ActiveQuery
     */
    public function getUpdater(): ActiveQuery
    {
        return $this->hasOne(
            Account::class,
            [
                'fld_id' => 'fld_updater_id',
            ]
        );
    }

    /**
     * @return array
     */
    public static function getTypes(): array
    {
        return static::$types;
    }

    /**
     * @return mixed
     */
    public function getType()
    {
        return self::$types[$this->fld_type_id];
    }

    /**
     * @return array
     */
    public static function getTypesButtonDropdown(): array
    {
        $result = [];

        foreach (static::$types as $type) {
            $worker = new self;
            $worker->fld_type_id = $type['fld_id'];

            if (Yii::$app->user->can('cms/worker/create', ['worker' => $worker])) {
                $result[] = [
                    'label' => $type['fld_name'],
                    'url' => ['/cms/worker/create', 'type_id' => $type['fld_id']]
                ];
            }
        }

        return $result;
    }

    /**
     * @return array
     */
    public static function getStatuses(): array
    {
        return static::$statuses;
    }

    /**
     * @return mixed
     */
    public function getStatus()
    {
        return static::$statuses[$this->fld_status_id];
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return implode(
            ' ',
            [
                $this->fld_last_name,
                $this->fld_first_name,
            ]);
    }

    /**
     * @return array
     */
    public static function actions(): array
    {
        return [
            self::ACTION_CREATE => [
                'fld_id' => self::ACTION_CREATE,
                'fld_name' => 'Utworzenie pracownika',
                'fld_color' => '#00a2f9',
            ],
            self::ACTION_UPDATE => [
                'fld_id' => self::ACTION_UPDATE,
                'fld_name' => 'Edytowanie pracownika',
                'fld_color' => '#00a2f9',
            ],
            self::ACTION_STATUS => [
                'fld_id' => self::ACTION_STATUS,
                'fld_name' => 'Zmiana statusu pracownika',
                'fld_color' => '#00a2f9',
            ],
        ];
    }

    /**
     * @param $action_id
     * @return array
     */
    public static function action($action_id): array
    {
        return static::actions()[$action_id];
    }

    /**
     * @return array
     */
    public function getAction(): array
    {
        return static::action($this->fld_action_id);
    }

    public function activate()
    {
        if ((int)$this->fld_status_id !== self::STATUS_ACTIVE) {
            $this->fld_status_id = self::STATUS_ACTIVE;

            if ($this->save() && $account = Account::findOne([
                'fld_model_id' => $this->fld_id,
                'fld_class_id' => 'cmsUser',
            ])) {
                $account->setStatus(self::STATUS_ACTIVE);
            }
        }
    }

    public function deactivate()
    {
        if ((int)$this->fld_status_id !== self::STATUS_INACTIVE) {
            $this->fld_status_id = self::STATUS_INACTIVE;

            if ($this->save() && $account = Account::findOne([
                'fld_worker_id' => $this->fld_id,
                'fld_class_id' => 'cmsUser',
            ])) {
                $account->setStatus(self::STATUS_INACTIVE);
            }
        }
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert): bool
    {
        if (parent::beforeSave($insert)) {
            if ($this->isNewRecord) {
                $this->fld_creator_id = Yii::$app->user->id;
            } else {
                $this->fld_updater_id = Yii::$app->user->id;
            }

            return true;
        }

        return false;
    }

    /**
     * @return bool
     */
    public function beforeDelete(): bool
    {
        if (parent::beforeDelete()) {
            $this->fld_deleted_at = date('Y-m-d H:i:s');
            $this->fld_deleter_id = Yii::$app->user->id;

            return true;
        }

        return false;
    }
}

src/views/log/_footer.php
<?php

use yii\helpers\Html;

?>

<div class="section">
	<div class="logs">
		<hr>
		<p>Utworzony <strong><?= \Yii::$app->formatter->asDate($model->fld_created_at, 'yyyy-MM-dd (HH:mm:ss)') ?></strong><?php if ($model->fld_creator_id): ?> przez <strong><?= Html::encode($model->creator->name) ?></strong><?php endif ?></p>
		<?php if ($model->fld_updated_at): ?>
			<p>Zmodyfikowany <strong><?= \Yii::$app->formatter->asDate($model->fld_updated_at, 'yyyy-MM-dd (HH:mm:ss)') ?></strong><?php if ($model->fld_updater_id): ?> przez <strong><?= Html::encode($model->updater->name) ?></strong><?php endif ?></p>
		<?php endif ?>
	</div>
</div>

src/views/log/_index.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;

?>

<div class="section">
	<?= GridView::widget([
		'dataProvider' => $dataProvider,
		'layout' => '{items}<div class="row"><div class="col-lg-6">{summary}</div><div class="col-lg-6">{pager}</div></div>',
		'tableOptions' => [
			'class' => 'table table-hover'
		],
		'pager' => [
			'options' => [
				'class' => 'pagination pull-right'
			]
		],
		'columns' => [
			[
				'label' => 'Nazwa akcji',
				'value' => function($data) {
					$main = '<strong>' . Html::encode($data->fld_action_name) . '</strong>';
					$adds =  strlen($data->fld_comment) ? '<br><small>' . Html::encode($data->fld_comment) . '</small>' : '';

					return  $main . $adds;
				},
				'format' => 'html',
				'headerOptions' => [
					'class' => 'col-main'
				],
				'contentOptions' => [
					'class' => 'col-main'
				],
			],
			[
				'label' => 'Obiekt',
				'value' => function($data) {
					$main = '';
					if (isset($data->fld_object_id)) {
						if (\Yii::$app->user->can('cms/' . $data->kind['fld_view'] . '/view', [$data->kind['fld_view'] . '_id' => $data->fld_object_id])) {
							$main =  Html::a($data->kind['fld_name'], [$data->kind['fld_view'], 'id' => $data->fld_object_id]);
						} else {
							$main =  $data->kind['fld_name'];
						}
					}

					return $main;
				},
				'format' => 'html',
				'headerOptions' => [
					'class' => 'col-sm'
				],
				'contentOptions' => [
					'class' => 'col-sm'
				],
			],
			[
				'label' => 'Data i czas',
				'value' => function($data) {
					$main = Yii::$app->formatter->asDate($data->fld_created_at, 'yyyy-MM-dd');
					$adds = '<br><small>' . Yii::$app->formatter->asTime($data->fld_created_at, 'HH:mm:ss') . '</small>';

					return $main . $adds;
				},
				'format' => 'html',
				'headerOptions' => [
					'class' => 'col-sm text-right'
				],
				'contentOptions' => [
					'class' => 'col-sm text-right'
				],
			],
			[
				'label' => 'Użytkownik',
				'value' => function($data) {
					$main = '';
					if (isset($data->fld_creator_id)) {
						if (isset($data->creator->fld_worker_id) && \Yii::$app->user->can('cms/worker/view', ['worker_id' => $data->creator->fld_worker_id])) {
							$main = Html::a(Html::encode($data->creator->name), ['/cms/worker/view', 'id' => $data->creator->fld_worker_id]);
						} else {
							$main = Html::encode($data->creator->name);
						}
					}

					return $main;
				},
				'format' => 'html',
				'headerOptions' => [
					'class' => 'col-md text-right'
				],
				'contentOptions' => [
					'class' => 'col-md text-right'
				],
			],
		],
	]); ?>
</div>

src/views/log/_summary.php
<?php

namespace datait\widgets;

?>

<div class="section">
</div>

src/views/log/index.php
<?php

use datait\fractal\models\Log;
use yii\helpers\Html;
use yii\bootstrap\Tabs;

?>

<?php
	$this->title = 'Logi';
?>

<h1><?= Html::encode($this->title) ?></h1>

<?php
	$dataProvider = new \yii\data\ActiveDataProvider([
		'query' => Log::find()->joinWith('creator')->orderBy('fld_id DESC')
	]);

	$items[] = [
		'label' => 'Logi',
		'content' => $this->render('/log/_index', ['dataProvider' => $dataProvider]),
		'active' => !isset($active) || (isset($active) && $active == 'logs') ? true : false,
		'headerOptions' => ['class' => 'main'],
	];

	$items[] = [
		'label' => 'Podsumowanie',
		'content' => $this->render('/log/_summary', ['dataProvider' => $dataProvider]),
		'active' => isset($active) && $active == 'summary' ? true : false,
		'headerOptions' => ['class' => 'pull-right'],
	];

	echo Tabs::widget([
		'items' => $items,
		'encodeLabels' => false,
	]);
?>